### ISSUE TITLE
TODO(12/05/2017)

### ISSUE THREAD

**Issue by zhengezhao** [zhengezhao/earthquake#1]
- [x] fix the white lines in the query.html
- [x] uuid doesn't work with the same username
- [ ] need a training tutorial to tell user if he is doing the right answer
- [x] fix the bug that 5 pairs not from the same eq
- [x] remove the first rule of the four rules(BHinge as the main and Fiber as two options)
- [x] a static image instead of dynamic images for the start page
- [x] clock to the user study
- [ ] set up user study similar to [paper](http://cmci.colorado.edu/visualab/papers/colordiff_vis2017.pdf) 
- [x] github backup
- [x] bug in the maxshift(the top 1 should be itself)
- [x] show the whole eq instead of the segments and align them such that the resulted parts are aligned and has the same length
- [x]  put the time in a js file
- [ ]  visual-identify css file 
- [x] clock if timeout, block the images
- [ ] ask Helen for criticism
- [ ] description of the earthquakes in the training data
- [ ] make the questions more
- [ ]  talk to IRB, UA email Matt
- [ ] make clustering by keep picking up windows (LSH)
- [ ] add obvious options to throw bad data
- [ ] align the similar part together
- [ ] 4 max value from one earthquake
- [ ] how to deal with the query which is longer than the earthquake itself: pad the original eq with zeros, not report that earthquake, crop the eq
- [ ] clock in the training session, not the real test
